function pyIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function pyConstIdentifier(name) {
  return pyIdentifier(name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function pyLiteral(value) {
  if (value === undefined || value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (Array.isArray(value)) return `[${value.map(pyLiteral).join(', ')}]`;
  if (typeof value === 'object') {
    return `{${Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${JSON.stringify(key)}: ${pyLiteral(item)}`)
      .join(', ')}}`;
  }
  return 'None';
}

function pyType(type) {
  if (!type) return 'Any';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `frozenset[${pyType(type.item)}]`;
    if (type.kind === 'list') return `tuple[${pyType(type.item)}, ...]`;
    if (type.kind === 'map') return `Mapping[${pyType(type.key)}, ${pyType(type.value)}]`;
    if (type.kind === 'ref') return pyIdentifier(type.name);
    return 'Any';
  }
  const primitive = { Text: 'str', String: 'str', Bool: 'bool', Boolean: 'bool', Int: 'int', Float: 'float', Number: 'float', Instant: 'str', Json: 'Any', Patch: 'list[FrontierPatchOperation]' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `frozenset[${pyType(set[1].trim())}]`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `tuple[${pyType(list[1].trim())}, ...]`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `Mapping[${pyType(map[1].trim())}, ${pyType(map[2].trim())}]`;
  return pyIdentifier(type);
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toPythonAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-python.';
  const declarations = [];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.fields?.length) declarations.push(dataclassItem(node, node.fields));
    if (node.kind === 'entity') declarations.push(dataclassItem(node, node.fields));
    if (node.kind === 'capability') declarations.push({
      kind: 'capabilityDescriptor',
      name: `${pyConstIdentifier(node.name)}_CAPABILITY`,
      value: {
        capability: node.capability,
        category: node.category,
        input: node.input,
        returns: node.returns,
        effects: node.effects ?? [],
        resources: node.resources ?? [],
        adapters: node.adapters ?? [],
        unsupported_targets: node.unsupportedTargets ?? []
      },
      sourceRef: sourceRef(node)
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      declarations.push({
        kind: 'function',
        name: pyIdentifier(node.name),
        stateType: 'Any',
        inputType: pyType(node.input),
        envType: 'Mapping[str, Any] | None',
        returnType: pyType(node.returns ?? 'Patch'),
        body: ['return []'],
        sourceRef: sourceRef(node)
      });
    }
  }
  return { kind: 'python.module', banner, declarations };
}

export function renderPythonAst(ast) {
  const lines = [];
  lines.push(`# ${ast.banner}`, 'from __future__ import annotations', '', 'from dataclasses import dataclass', 'from typing import Any, Mapping, TypedDict', '', 'class FrontierPatchOperation(TypedDict, total=False):', '    op: str', '    path: str', '    value: Any', '');
  for (const declaration of ast.declarations) {
    if (declaration.kind === 'dataclass') renderDataclass(lines, declaration);
    if (declaration.kind === 'capabilityDescriptor') lines.push(`${declaration.name}: Mapping[str, Any] = ${pyLiteral(declaration.value)}`, '');
  }
  for (const declaration of ast.declarations) {
    if (declaration.kind === 'function') {
      lines.push(`def ${declaration.name}(state: ${declaration.stateType}, input: ${declaration.inputType}, env: ${declaration.envType} = None) -> ${declaration.returnType}:`);
      for (const statement of declaration.body) lines.push(`    ${statement}`);
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export function emitPython(document, options = {}) {
  return renderPythonAst(toPythonAst(document, options));
}

function dataclassItem(node, fields) {
  return {
    kind: 'dataclass',
    name: pyIdentifier(node.name),
    fields: fields.map((field) => ({ name: pyIdentifier(field.name), type: pyType(field.type) })),
    sourceRef: sourceRef(node, { regionIds: fields.map((field) => field.id) })
  };
}

function renderDataclass(lines, declaration) {
  lines.push('@dataclass(frozen=True)', `class ${declaration.name}:`);
  if (!declaration.fields.length) lines.push('    pass');
  for (const field of declaration.fields) lines.push(`    ${field.name}: ${field.type}`);
  lines.push('');
}
