import { externDescriptorItem, externRunnerItem } from './extern.js';
import { pythonActionBodyStatements } from './action-body.js';
function pyIdentifier(name) {
  const identifier = String(name ?? 'unknown').replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function pyConstIdentifier(name) {
  return pyIdentifier(name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function pyLiteral(value) {
  if (value === undefined || value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (Array.isArray(value)) return `[${value.map(pyLiteral).join(', ')}]`;
  if (typeof value === 'object') {
    return `{${Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${JSON.stringify(key)}: ${pyLiteral(item)}`)
      .join(', ')}}`;
  }
  return 'None';
}

function pyType(type) {
  if (!type) return 'Any';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `frozenset[${pyType(type.item)}]`;
    if (type.kind === 'list') return `tuple[${pyType(type.item)}, ...]`;
    if (type.kind === 'map') return `Mapping[${pyType(type.key)}, ${pyType(type.value)}]`;
    if (type.kind === 'ref') return pyIdentifier(type.name);
    return 'Any';
  }
  const primitive = { Text: 'str', String: 'str', Bool: 'bool', Boolean: 'bool', Int: 'int', Float: 'float', Number: 'float', Instant: 'str', Json: 'Any', Patch: 'list[FrontierPatchOperation]' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `frozenset[${pyType(set[1].trim())}]`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `tuple[${pyType(list[1].trim())}, ...]`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `Mapping[${pyType(map[1].trim())}, ${pyType(map[2].trim())}]`;
  return pyIdentifier(type);
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toPythonAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-python.';
  const declarations = [];
  const stateType = firstStateType(document);
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.fields?.length) declarations.push(dataclassItem(node, node.fields));
    if (node.kind === 'entity') declarations.push(dataclassItem(node, node.fields));
    if (node.kind === 'state') declarations.push(stateItem(node));
    if (node.kind === 'capability') declarations.push({
      kind: 'capabilityDescriptor',
      name: `${pyConstIdentifier(node.name)}_CAPABILITY`,
      value: {
        capability: node.capability,
        category: node.category,
        input: node.input,
        returns: node.returns,
        effects: node.effects ?? [],
        resources: node.resources ?? [],
        adapters: node.adapters ?? [],
        unsupported_targets: node.unsupportedTargets ?? []
      },
      sourceRef: sourceRef(node)
    });
    if (node.kind === 'effect') declarations.push(effectDescriptorItem(node), effectRunnerItem(node));
    if (node.kind === 'extern') declarations.push(
      externDescriptorItem(node, { pyConstIdentifier, sourceRef }),
      externRunnerItem(node, { pyIdentifier, pyType, sourceRef })
    );
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      declarations.push({
        kind: 'function',
        name: pyIdentifier(node.name),
        stateType,
        inputType: pyType(node.input),
        envType: 'Mapping[str, Any] | None',
        returnType: pyType(node.returns ?? 'Patch'),
        body: pythonActionBodyStatements(node, { pyIdentifier, pyLiteral }),
        sourceRef: sourceRef(node)
      });
    }
  }
  return { kind: 'python.module', banner, declarations };
}

export function renderPythonAst(ast) {
  return renderPythonAstWithSourceMap(ast).code;
}

export function renderPythonAstWithSourceMap(ast, options = {}) {
  const lines = [];
  const mappings = [];
  const target = normalizeTarget(options, 'python');
  lines.push(`# ${ast.banner}`, 'from __future__ import annotations', '', 'from dataclasses import dataclass', 'from typing import Any, Mapping, TypedDict', '', 'class FrontierPatchOperation(TypedDict, total=False):', '    op: str', '    path: str', '    value: Any', '');
  ast.declarations.forEach((declaration, index) => {
    if (declaration.kind === 'function') return;
    renderMappedPythonDeclaration(lines, mappings, declaration, index, target, options);
  });
  ast.declarations.forEach((declaration, index) => {
    if (declaration.kind !== 'function') return;
    renderMappedPythonDeclaration(lines, mappings, declaration, index, target, options);
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return {
    code,
    sourceMap: sourceMapEnvelope(ast, mappings, target, options, 'python', 'python-renderer-declaration-block')
  };
}

export function emitPython(document, options = {}) {
  return renderPythonAst(toPythonAst(document, options));
}

export function emitPythonWithSourceMap(document, options = {}) {
  const ast = toPythonAst(document, options);
  const result = renderPythonAstWithSourceMap(ast, {
    sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_python`,
    ...options
  });
  return { ...result, ast };
}

function dataclassItem(node, fields) {
  return {
    kind: 'dataclass',
    name: pyIdentifier(node.name),
    fields: fields.map((field) => ({ name: pyIdentifier(field.name), type: pyType(field.type) })),
    sourceRef: sourceRef(node, { regionIds: fields.map((field) => field.id) })
  };
}

function stateItem(node) {
  return {
    kind: 'dataclass',
    name: `${pyIdentifier(node.name)}State`,
    fields: (node.collections ?? []).map((collection) => ({ name: pyIdentifier(collection.name), type: pyType(collection.type) })),
    sourceRef: sourceRef(node, { regionIds: (node.collections ?? []).map((collection) => collection.id) })
  };
}

function effectDescriptorItem(node) {
  return {
    kind: 'effectDescriptor',
    name: `${pyConstIdentifier(node.name)}_EFFECT`,
    value: {
      name: node.name,
      capability: node.capability,
      input: node.input,
      returns: node.returns,
      resources: node.resources ?? [],
      semantics: node.semantics
    },
    sourceRef: sourceRef(node)
  };
}

function effectRunnerItem(node) {
  return {
    kind: 'effectRunner',
    name: `run_${pyIdentifier(node.name)}_effect`,
    inputType: pyType(node.input ?? 'Json'),
    returnType: pyType(node.returns ?? 'Json'),
    value: {
      name: node.name,
      capability: node.capability,
      resources: node.resources ?? [],
      semantics: node.semantics
    },
    sourceRef: sourceRef(node)
  };
}

function firstStateType(document) {
  const state = Object.values(document.nodes).find((node) => node.kind === 'state');
  return state ? `${pyIdentifier(state.name)}State` : 'Any';
}

function renderDataclass(lines, declaration) {
  lines.push('@dataclass(frozen=True)', `class ${declaration.name}:`);
  if (!declaration.fields.length) lines.push('    pass');
  for (const field of declaration.fields) lines.push(`    ${field.name}: ${field.type}`);
  lines.push('');
}

function renderMappedPythonDeclaration(lines, mappings, declaration, index, target, options) {
  const startLine = lines.length + 1;
  const startIndex = lines.length;
  renderPythonDeclaration(lines, declaration);
  const generatedSpan = declarationBlockSpan(lines, startIndex, startLine, declaration, target, options.targetPath);
  if (declaration.sourceRef?.semanticNodeId && generatedSpan) {
    mappings.push(sourceMapMapping(declaration, index, generatedSpan, target, options, 'python-renderer-declaration-block'));
  }
}

function renderPythonDeclaration(lines, declaration) {
  if (declaration.kind === 'dataclass') renderDataclass(lines, declaration);
  if (declaration.kind === 'capabilityDescriptor') lines.push(`${declaration.name}: Mapping[str, Any] = ${pyLiteral(declaration.value)}`, '');
  if (declaration.kind === 'effectDescriptor') lines.push(`${declaration.name}: Mapping[str, Any] = ${pyLiteral(declaration.value)}`, '');
  if (declaration.kind === 'externDescriptor') lines.push(`${declaration.name}: Mapping[str, Any] = ${pyLiteral(declaration.value)}`, '');
  if (declaration.kind === 'effectRunner') {
    lines.push(`def ${declaration.name}(input: ${declaration.inputType}, env: Mapping[str, Any]) -> ${declaration.returnType}:`);
    lines.push('    invoke = env["invoke"]');
    lines.push(`    return invoke(${pyLiteral(declaration.value.capability)}, input, ${pyLiteral({ effect: declaration.value.name, resources: declaration.value.resources, semantics: declaration.value.semantics ?? null })})`);
    lines.push('');
  }
  if (declaration.kind === 'externRunner') {
    lines.push(`def ${declaration.name}(input: ${declaration.inputType}, env: Mapping[str, Any]) -> ${declaration.returnType}:`);
    lines.push('    call_extern = env["callExtern"]');
    lines.push(`    return call_extern(${pyLiteral(declaration.value.symbol)}, input, ${pyLiteral({ extern: declaration.value.name, language: declaration.value.language, effects: declaration.value.effects, resources: declaration.value.resources })})`);
    lines.push('');
  }
  if (declaration.kind === 'function') {
    lines.push(`def ${declaration.name}(state: ${declaration.stateType}, input: ${declaration.inputType}, env: ${declaration.envType} = None) -> ${declaration.returnType}:`);
    for (const statement of declaration.body) lines.push(`    ${statement}`);
    lines.push('');
  }
}

function declarationBlockSpan(lines, startIndex, startLine, declaration, target, targetPath) {
  let endIndex = lines.length - 1;
  while (endIndex >= startIndex && lines[endIndex] === '') endIndex -= 1;
  if (endIndex < startIndex) return undefined;
  return definedObject({
    path: targetPath,
    target,
    targetPath,
    generatedName: declaration.name,
    startLine,
    startColumn: 1,
    endLine: endIndex + 1,
    endColumn: lines[endIndex].length + 1
  });
}

function normalizeTarget(options, language) {
  return definedObject({
    ...(options.target ?? {}),
    language: options.target?.language ?? language,
    emitPath: options.target?.emitPath ?? options.targetPath
  });
}

function sourceMapMapping(declaration, index, generatedSpan, target, options, strategy) {
  return definedObject({
    id: `map_${idFragment(declaration.sourceRef.semanticNodeId)}_${index}`,
    semanticNodeId: declaration.sourceRef.semanticNodeId,
    nativeSourceId: options.nativeSourceId,
    semanticSymbolId: options.semanticSymbolIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    semanticOccurrenceId: options.semanticOccurrenceIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    sourceSpan: options.sourceSpansBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    generatedSpan,
    target,
    generatedName: declaration.name,
    evidenceIds: options.evidence?.map((record) => record.id),
    lossIds: options.lossIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    precision: 'declaration',
    metadata: {
      generatedSpanStrategy: strategy,
      sourceMapImplication: 'Generated span covers the emitted declaration block and is not token exact.',
      semanticIndexImplication: 'Mapping is anchored by semanticNodeId; symbol and occurrence ids are optional caller-provided links.',
      lossAccountingImplication: 'No loss ids are inferred by the printer; caller-provided loss ids are copied when available.',
      mergeReadinessImplication: 'Suitable for declaration-level overlap review, not fine-grained token merge admission.',
      semanticNodeKind: declaration.sourceRef.semanticNodeKind,
      semanticNodeName: declaration.sourceRef.semanticNodeName,
      regionIds: declaration.sourceRef.regionIds
    }
  });
}

function sourceMapEnvelope(ast, mappings, target, options, language, strategy) {
  return definedObject({
    kind: 'frontier.lang.sourceMap',
    version: 1,
    id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_${language}`,
    sourcePath: options.sourcePath,
    sourceHash: options.sourceHash,
    target,
    targetPath: options.targetPath,
    targetHash: options.targetHash,
    semanticIndexId: options.semanticIndexId,
    universalAstId: options.universalAstId,
    nativeAstId: options.nativeAstId,
    nativeSourceId: options.nativeSourceId,
    mappings,
    evidence: options.evidence ?? [],
    metadata: {
      generatedSpanStrategy: strategy,
      precision: 'declaration',
      sourceMapImplication: 'Approximate generated spans are emitted as sidecar mappings without rewriting the printer.',
      semanticIndexImplication: 'Semantic index linkage remains optional and can be attached through ids supplied in options.',
      lossAccountingImplication: 'The renderer does not create loss records; existing loss ids can be associated per semantic node.',
      mergeReadinessImplication: 'Declaration-block mappings can guide generated-output review but should not be treated as token-exact source maps.',
      ...(options.metadata ?? {})
    }
  });
}

function definedObject(object) {
  return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined));
}

function idFragment(value) {
  return pyIdentifier(String(value ?? 'unknown')).replace(/^_+/, '') || 'unknown';
}
