function pyIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function pyType(type) {
  if (!type) return 'Any';
  if (typeof type !== 'string') {
    if (type.kind === 'set') return `frozenset[${pyType(type.item)}]`;
    if (type.kind === 'list') return `tuple[${pyType(type.item)}, ...]`;
    if (type.kind === 'map') return `Mapping[${pyType(type.key)}, ${pyType(type.value)}]`;
    if (type.kind === 'ref') return pyIdentifier(type.name);
    return 'Any';
  }
  const primitive = { Text: 'str', String: 'str', Bool: 'bool', Boolean: 'bool', Int: 'int', Float: 'float', Number: 'float', Instant: 'str', Json: 'Any', Patch: 'list[FrontierPatchOperation]' };
  if (primitive[type]) return primitive[type];
  const set = /^Set<(.+)>$/.exec(type);
  if (set) return `frozenset[${pyType(set[1].trim())}]`;
  const list = /^List<(.+)>$/.exec(type);
  if (list) return `tuple[${pyType(list[1].trim())}, ...]`;
  const map = /^Map<(.+),\s*(.+)>$/.exec(type);
  if (map) return `Mapping[${pyType(map[1].trim())}, ${pyType(map[2].trim())}]`;
  return pyIdentifier(type);
}

export function emitPython(document, options = {}) {
  const lines = [];
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-python.';
  lines.push(`# ${banner}`, 'from __future__ import annotations', '', 'from dataclasses import dataclass', 'from typing import Any, Mapping, TypedDict', '', 'class FrontierPatchOperation(TypedDict, total=False):', '    op: str', '    path: str', '    value: Any', '');
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.fields?.length) emitDataclass(lines, node.name, node.fields);
    if (node.kind === 'entity') emitDataclass(lines, node.name, node.fields);
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') lines.push(`def ${pyIdentifier(node.name)}(state: Any, input: ${pyType(node.input)}, env: Mapping[str, Any] | None = None) -> ${pyType(node.returns ?? 'Patch')}:`, '    return []', '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitDataclass(lines, name, fields) {
  lines.push('@dataclass(frozen=True)', `class ${pyIdentifier(name)}:`);
  if (!fields.length) lines.push('    pass');
  for (const field of fields) lines.push(`    ${pyIdentifier(field.name)}: ${pyType(field.type)}`);
  lines.push('');
}
